### PR TITLE
added responsiveness

### PR DESCRIPTION
**Pull request by Durga-prasad-1**
@pooja-gera i have complete the task , which is making the website responsive . please check it and if there are any conflicts then let me know.

### CODE REVIEW

**Comment by pooja-gera** [comment]
LGTM, https://forms.gle/wFVCMgDEyDUqQ1HZ6 please fill out this form with your t-shirt size, you'll receive it within 2 weeks of the completion of hacktoberfest 2024. Thankyou @Durga-prasad-1 you're awesome! 🤩

**Comment by Durga-prasad-1** [comment]
@pooja-gera Thank you so much🤩! I'm really excited about the T-shirt and had a great time participating in Hacktoberfest. However, I heard that T-shirts might not be provided this year. Could you clarify that for me?

**Comment by pooja-gera** [comment]
Sure sure, these are not official hacktoberfest tshirts. I was building algorithm-finder for myself then I thought maybe I can help a few people get started with open source since this was an easy to understand codebase. Hence, opened a few issues and invited contributions. 

Funding these from my own pocket haha! 🥰

**Comment by Durga-prasad-1** [comment]
Wow, that’s amazing! Thank you so much for doing this and for being so generous. It’s awesome that you created something to help others get started with open source! You're truly inspiring! 🤩 and I have filled the form

**Pull request merged**
