### PR TITLE
[Optimization]: Path traversal to visit each node in the path flow exactly once

### PR DESCRIPTION
**Pull request by Ananya-Bhardwaj**
This PR solves issue #3 by assigning the current node in the flow path while iterating through the path itself, eliminating the need to find the node from the root, each time.

### CODE REVIEW

**Comment by pooja-gera** [comment]
Hey @Ananya-Bhardwaj the thing you were mentioning about Yes and No buttons being available for all, we can add a check here only, when you are setting the current node to yes or no branch while clicking the yes / no button, add these conditions

For Yes button click: 
if `currNode.yes !== null` then set `currNode` to be `currNode.yes` 
else disable yes button 

For No button click
if `currNode.no !== null` then set `currNode` to be `currNode.no` 
else disable yes button

**Comment by Ananya-Bhardwaj** [comment]
Okay I will add this

**Comment by pooja-gera** [comment]
Hey @Ananya-Bhardwaj can you resolve the merge conflicts before we merge this branch? ^.^

**Comment by Ananya-Bhardwaj** [comment]
Sure, I'll check

**Comment by pooja-gera** [comment]
LGTM, https://forms.gle/wFVCMgDEyDUqQ1HZ6 please fill out this form with your t-shirt size, you'll receive it within 2 weeks of the completion of hacktoberfest 2024. Thankyou @Ananya-Bhardwaj you're awesome! 🤩

**Pull request merged**
